services:
  db:
    image: postgres:latest
    container_name: sleep-postgres
    environment:
      POSTGRES_DB: sleepdb
      POSTGRES_USER: sleepuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
